repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/HunterMcGushion/docstr_coverage
    rev: v2.3.2
    hooks:
      - id: docstr-coverage
        args: [--verbose, "0", --fail-under=100, src/]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        always_run: true
