"""
Tests for Variants type.
"""

import shutil
from datetime import datetime

import pytest
from conftest import FIXTURES_DIR

from stargazer.types import Variants
from stargazer.utils.storage import default_client
from stargazer.utils.ipfile import IpFile


@pytest.mark.asyncio
async def test_variants_fetch():
    """Test fetch() downloads VCF and index files to cache."""
    # Setup: Create dummy VCF files for testing
    # Note: Real VCF fixtures will be generated by variant caller tasks
    vcf_fixture = FIXTURES_DIR / "dummy.vcf"
    tbi_fixture = FIXTURES_DIR / "dummy.vcf.tbi"

    # Create minimal dummy files
    vcf_fixture.write_text(
        "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
    )
    tbi_fixture.write_text("dummy_index")

    try:
        # Pre-populate cache using default_client
        test_cid_vcf = "QmTestVcf"
        test_cid_tbi = "QmTestTbi"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        cached_tbi = default_client.local_dir / test_cid_tbi
        shutil.copy(vcf_fixture, cached_vcf)
        shutil.copy(tbi_fixture, cached_tbi)

        # Create IpFile objects for VCF and TBI
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="NA12829_TP53.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "vcf",
                "sample_id": "NA12829",
                "caller": "deepvariant",
                "variant_type": "vcf",
            },
            created_at=datetime.now(),
        )

        tbi_file = IpFile(
            id="test-tbi-id",
            cid=test_cid_tbi,
            name="NA12829_TP53.vcf.tbi",
            size=cached_tbi.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "index",
                "sample_id": "NA12829",
            },
            created_at=datetime.now(),
        )

        # Create Variants object with component fields
        variants = Variants(
            sample_id="NA12829",
            vcf=vcf_file,
            index=tbi_file,
        )

        # Run fetch()
        cache_dir = await variants.fetch()

        # Verify cache directory returned
        assert cache_dir == default_client.local_dir
        assert cache_dir.exists()

        # Verify both files are in cache (check local_path is set)
        assert variants.vcf.local_path is not None
        assert variants.vcf.local_path.exists()
        assert variants.index.local_path is not None
        assert variants.index.local_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
        if cached_tbi.exists():
            cached_tbi.unlink()
    finally:
        # Clean up dummy fixtures
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_vcf_path():
    """Test direct access to vcf component returns correct path."""
    # Setup: Create dummy VCF
    vcf_fixture = FIXTURES_DIR / "dummy2.vcf"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")

    try:
        test_cid_vcf = "QmTestVcfGetPath"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        shutil.copy(vcf_fixture, cached_vcf)

        # Create IpFile object with local_path set (as if already downloaded)
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "vcf",
                "sample_id": "NA12829",
            },
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        # Create Variants object with vcf component
        variants = Variants(
            sample_id="NA12829",
            vcf=vcf_file,
        )

        # Test direct field access
        vcf_path = variants.vcf.local_path
        assert vcf_path == cached_vcf
        assert vcf_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_index_path():
    """Test direct access to index component returns correct path when present."""
    # Setup: Create dummy VCF and index
    vcf_fixture = FIXTURES_DIR / "dummy3.vcf"
    tbi_fixture = FIXTURES_DIR / "dummy3.vcf.tbi"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")
    tbi_fixture.write_text("dummy_index")

    try:
        test_cid_vcf = "QmTestVcfGetIndex"
        test_cid_tbi = "QmTestTbiGetIndex"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        cached_tbi = default_client.local_dir / test_cid_tbi
        shutil.copy(vcf_fixture, cached_vcf)
        shutil.copy(tbi_fixture, cached_tbi)

        # Create IpFile objects with local_path set
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "vcf",
                "sample_id": "NA12829",
            },
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        tbi_file = IpFile(
            id="test-tbi-id",
            cid=test_cid_tbi,
            name="test.vcf.tbi",
            size=cached_tbi.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "index",
                "sample_id": "NA12829",
            },
            created_at=datetime.now(),
            local_path=cached_tbi,
        )

        # Create Variants object with both components
        variants = Variants(
            sample_id="NA12829",
            vcf=vcf_file,
            index=tbi_file,
        )

        # Test direct field access
        index_path = variants.index.local_path
        assert index_path == cached_tbi
        assert index_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
        if cached_tbi.exists():
            cached_tbi.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_index_path_none():
    """Test index component is None when index not present."""
    # Setup: Create dummy VCF only (no index)
    vcf_fixture = FIXTURES_DIR / "dummy4.vcf"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")

    try:
        test_cid_vcf = "QmTestVcfNoIndex"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        shutil.copy(vcf_fixture, cached_vcf)

        # Create IpFile object with local_path set
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={
                "type": "variants",
                "component": "vcf",
                "sample_id": "NA12829",
            },
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        # Create Variants object without index
        variants = Variants(
            sample_id="NA12829",
            vcf=vcf_file,
        )

        # Test index is None
        assert variants.index is None

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_update_components():
    """Test update_vcf() and update_index() upload files."""
    # Setup: Create dummy files
    vcf_fixture = FIXTURES_DIR / "dummy5.vcf"
    tbi_fixture = FIXTURES_DIR / "dummy5.vcf.tbi"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")
    tbi_fixture.write_text("dummy_index")

    try:
        # Create empty Variants object
        variants = Variants(sample_id="NA12829")

        # Update vcf component
        vcf_ipfile = await variants.update_vcf(
            vcf_fixture,
            caller="deepvariant",
            variant_type="vcf",
            build="GRCh38",
        )

        # Update index component
        tbi_ipfile = await variants.update_index(tbi_fixture)

        # Verify vcf component was set
        assert variants.vcf is not None
        assert variants.vcf == vcf_ipfile
        assert variants.vcf.keyvalues.get("type") == "variants"
        assert variants.vcf.keyvalues.get("component") == "vcf"
        assert variants.vcf.keyvalues.get("sample_id") == "NA12829"
        assert variants.vcf.keyvalues.get("caller") == "deepvariant"
        assert variants.vcf.keyvalues.get("variant_type") == "vcf"
        assert variants.vcf.keyvalues.get("build") == "GRCh38"

        # Verify index component was set
        assert variants.index is not None
        assert variants.index == tbi_ipfile
        assert variants.index.keyvalues.get("type") == "variants"
        assert variants.index.keyvalues.get("component") == "index"
        assert variants.index.keyvalues.get("sample_id") == "NA12829"

        # Cleanup cache (files may have been copied there)
        if variants.vcf.local_path and variants.vcf.local_path.exists():
            variants.vcf.local_path.unlink()
        if variants.index.local_path and variants.index.local_path.exists():
            variants.index.local_path.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_fetch_empty():
    """Test fetch() raises ValueError for empty variants."""
    variants = Variants(sample_id="NA12829")

    with pytest.raises(ValueError, match="No files to fetch"):
        await variants.fetch()


@pytest.mark.asyncio
async def test_variants_get_vcf_path_not_found():
    """Test that vcf is None when component not set."""
    variants = Variants(sample_id="NA12829")

    assert variants.vcf is None


@pytest.mark.asyncio
async def test_variants_get_vcf_path_not_cached():
    """Test that local_path is None when file not fetched yet."""
    # Create IpFile without local_path (not fetched yet)
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="test.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
        },
        created_at=datetime.now(),
        local_path=None,  # Not downloaded yet
    )

    variants = Variants(sample_id="NA12829", vcf=vcf_file)

    # local_path should be None
    assert variants.vcf.local_path is None


@pytest.mark.asyncio
async def test_variants_properties():
    """Test Variants properties read from vcf file keyvalues."""
    # Create VCF file with metadata in keyvalues
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="test.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
            "caller": "deepvariant",
            "variant_type": "gvcf",
        },
        created_at=datetime.now(),
    )

    variants = Variants(
        sample_id="NA12829",
        vcf=vcf_file,
    )

    # Properties should read from vcf keyvalues
    assert variants.caller == "deepvariant"
    assert variants.is_gvcf is True

    # Create Variants with VCF type
    vcf_file2 = IpFile(
        id="test-vcf-id-2",
        cid="QmTest2",
        name="test2.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
            "caller": "haplotypecaller",
            "variant_type": "vcf",
        },
        created_at=datetime.now(),
    )

    variants2 = Variants(sample_id="NA12829", vcf=vcf_file2)

    assert variants2.caller == "haplotypecaller"
    assert variants2.is_gvcf is False

    # Test with missing metadata
    vcf_file3 = IpFile(
        id="test-vcf-id-3",
        cid="QmTest3",
        name="test3.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
        },
        created_at=datetime.now(),
    )

    variants3 = Variants(sample_id="NA12829", vcf=vcf_file3)

    assert variants3.caller == "unknown"
    assert variants3.is_gvcf is False


@pytest.mark.asyncio
async def test_variants_multi_sample():
    """Test multi-sample VCF properties."""
    # Create multi-sample VCF
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="multi.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
            "sample_count": "3",
            "source_samples": "NA12829,NA12830,NA12831",
        },
        created_at=datetime.now(),
    )

    variants = Variants(
        sample_id="NA12829",
        vcf=vcf_file,
    )

    # Should be multi-sample
    assert variants.is_multi_sample is True
    assert variants.source_samples == ["NA12829", "NA12830", "NA12831"]

    # Create single-sample VCF
    vcf_file2 = IpFile(
        id="test-vcf-id-2",
        cid="QmTest2",
        name="single.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
            "sample_count": "1",
        },
        created_at=datetime.now(),
    )

    variants2 = Variants(sample_id="NA12829", vcf=vcf_file2)

    # Should be single-sample
    assert variants2.is_multi_sample is False
    assert variants2.source_samples == ["NA12829"]


@pytest.mark.asyncio
async def test_variants_source_samples_default():
    """Test source_samples returns sample_id when metadata not set."""
    # Create VCF without source_samples metadata
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="test.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "component": "vcf",
        },
        created_at=datetime.now(),
    )

    variants = Variants(sample_id="NA12829", vcf=vcf_file)

    # Should return default list with sample_id
    assert variants.source_samples == ["NA12829"]
