"""
Tests for Variants type.
"""

import shutil
from datetime import datetime

import pytest
from config import TEST_ROOT

from stargazer.types import Variants
from stargazer.utils.pinata import IpFile, default_client


@pytest.mark.asyncio
async def test_variants_fetch():
    """Test fetch() downloads VCF and index files to cache."""
    # Setup: Create dummy VCF files for testing
    # Note: Real VCF fixtures will be generated by variant caller tasks
    vcf_fixture = TEST_ROOT / "fixtures" / "dummy.vcf"
    tbi_fixture = TEST_ROOT / "fixtures" / "dummy.vcf.tbi"

    # Create minimal dummy files
    vcf_fixture.write_text(
        "##fileformat=VCFv4.2\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n"
    )
    tbi_fixture.write_text("dummy_index")

    try:
        # Pre-populate cache using default_client
        test_cid_vcf = "QmTestVcf"
        test_cid_tbi = "QmTestTbi"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        cached_tbi = default_client.local_dir / test_cid_tbi
        shutil.copy(vcf_fixture, cached_vcf)
        shutil.copy(tbi_fixture, cached_tbi)

        # Create IpFile objects for VCF and TBI
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="NA12829_TP53.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={
                "type": "variants",
                "sample_id": "NA12829",
                "caller": "deepvariant",
                "variant_type": "vcf",
            },
            created_at=datetime.now(),
        )

        tbi_file = IpFile(
            id="test-tbi-id",
            cid=test_cid_tbi,
            name="NA12829_TP53.vcf.tbi",
            size=cached_tbi.stat().st_size,
            keyvalues={"type": "variants", "sample_id": "NA12829"},
            created_at=datetime.now(),
        )

        # Create Variants object
        variants = Variants(
            sample_id="NA12829",
            vcf_name="NA12829_TP53.vcf",
            files=[vcf_file, tbi_file],
        )

        # Run fetch()
        cache_dir = await variants.fetch()

        # Verify cache directory returned
        assert cache_dir == default_client.local_dir
        assert cache_dir.exists()

        # Verify both files are in cache (check local_path is set)
        assert vcf_file.local_path is not None
        assert vcf_file.local_path.exists()
        assert tbi_file.local_path is not None
        assert tbi_file.local_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
        if cached_tbi.exists():
            cached_tbi.unlink()
    finally:
        # Clean up dummy fixtures
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_vcf_path():
    """Test get_vcf_path() returns correct path."""
    # Setup: Create dummy VCF
    vcf_fixture = TEST_ROOT / "fixtures" / "dummy2.vcf"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")

    try:
        test_cid_vcf = "QmTestVcfGetPath"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        shutil.copy(vcf_fixture, cached_vcf)

        # Create IpFile object with local_path set (as if already downloaded)
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={"type": "variants", "sample_id": "NA12829"},
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        # Create Variants object
        variants = Variants(
            sample_id="NA12829",
            vcf_name="test.vcf",
            files=[vcf_file],
        )

        # Test get_vcf_path()
        vcf_path = variants.get_vcf_path()
        assert vcf_path == cached_vcf
        assert vcf_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_index_path():
    """Test get_index_path() returns correct path when present."""
    # Setup: Create dummy VCF and index
    vcf_fixture = TEST_ROOT / "fixtures" / "dummy3.vcf"
    tbi_fixture = TEST_ROOT / "fixtures" / "dummy3.vcf.tbi"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")
    tbi_fixture.write_text("dummy_index")

    try:
        test_cid_vcf = "QmTestVcfGetIndex"
        test_cid_tbi = "QmTestTbiGetIndex"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        cached_tbi = default_client.local_dir / test_cid_tbi
        shutil.copy(vcf_fixture, cached_vcf)
        shutil.copy(tbi_fixture, cached_tbi)

        # Create IpFile objects with local_path set
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={"type": "variants", "sample_id": "NA12829"},
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        tbi_file = IpFile(
            id="test-tbi-id",
            cid=test_cid_tbi,
            name="test.vcf.tbi",
            size=cached_tbi.stat().st_size,
            keyvalues={"type": "variants", "sample_id": "NA12829"},
            created_at=datetime.now(),
            local_path=cached_tbi,
        )

        # Create Variants object
        variants = Variants(
            sample_id="NA12829",
            vcf_name="test.vcf",
            files=[vcf_file, tbi_file],
        )

        # Test get_index_path()
        index_path = variants.get_index_path()
        assert index_path == cached_tbi
        assert index_path.exists()

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
        if cached_tbi.exists():
            cached_tbi.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_get_index_path_none():
    """Test get_index_path() returns None when index not present."""
    # Setup: Create dummy VCF only (no index)
    vcf_fixture = TEST_ROOT / "fixtures" / "dummy4.vcf"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")

    try:
        test_cid_vcf = "QmTestVcfNoIndex"
        default_client.local_dir.mkdir(parents=True, exist_ok=True)
        cached_vcf = default_client.local_dir / test_cid_vcf
        shutil.copy(vcf_fixture, cached_vcf)

        # Create IpFile object with local_path set
        vcf_file = IpFile(
            id="test-vcf-id",
            cid=test_cid_vcf,
            name="test.vcf",
            size=cached_vcf.stat().st_size,
            keyvalues={"type": "variants", "sample_id": "NA12829"},
            created_at=datetime.now(),
            local_path=cached_vcf,
        )

        # Create Variants object without index
        variants = Variants(
            sample_id="NA12829",
            vcf_name="test.vcf",
            files=[vcf_file],
        )

        # Test get_index_path() returns None
        index_path = variants.get_index_path()
        assert index_path is None

        # Cleanup
        if cached_vcf.exists():
            cached_vcf.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_add_files():
    """Test add_files() uploads VCF and index files with metadata."""
    # Setup: Create dummy files
    vcf_fixture = TEST_ROOT / "fixtures" / "dummy5.vcf"
    tbi_fixture = TEST_ROOT / "fixtures" / "dummy5.vcf.tbi"
    vcf_fixture.write_text("##fileformat=VCFv4.2\n")
    tbi_fixture.write_text("dummy_index")

    try:
        # Create empty Variants object
        variants = Variants(sample_id="NA12829", vcf_name="test.vcf")

        # Add files (in local_only mode, this should copy to cache)
        keyvalues = {
            "type": "variants",
            "sample_id": "NA12829",
            "caller": "deepvariant",
            "variant_type": "vcf",
            "build": "GRCh38",
        }
        await variants.add_files(
            file_paths=[vcf_fixture, tbi_fixture],
            keyvalues=keyvalues,
        )

        # Verify files were added
        assert len(variants.files) == 2

        # Verify metadata
        assert all(f.keyvalues.get("type") == "variants" for f in variants.files)
        assert all(f.keyvalues.get("sample_id") == "NA12829" for f in variants.files)
        assert all(f.keyvalues.get("caller") == "deepvariant" for f in variants.files)

        # Cleanup cache (files may have been copied there)
        for f in variants.files:
            if f.local_path and f.local_path.exists():
                f.local_path.unlink()
    finally:
        if vcf_fixture.exists():
            vcf_fixture.unlink()
        if tbi_fixture.exists():
            tbi_fixture.unlink()


@pytest.mark.asyncio
async def test_variants_add_files_empty_list():
    """Test add_files() raises ValueError for empty list."""
    variants = Variants(sample_id="NA12829", vcf_name="test.vcf")

    with pytest.raises(ValueError, match="No files to add"):
        await variants.add_files(file_paths=[], keyvalues={})


@pytest.mark.asyncio
async def test_variants_add_files_missing_file():
    """Test add_files() raises FileNotFoundError for missing files."""
    variants = Variants(sample_id="NA12829", vcf_name="test.vcf")

    with pytest.raises(FileNotFoundError, match="File not found"):
        await variants.add_files(
            file_paths=[TEST_ROOT / "fixtures" / "nonexistent.vcf"],
            keyvalues={"type": "variants"},
        )


@pytest.mark.asyncio
async def test_variants_fetch_empty():
    """Test fetch() raises ValueError for empty variants."""
    variants = Variants(sample_id="NA12829", vcf_name="test.vcf")

    with pytest.raises(ValueError, match="No files to fetch"):
        await variants.fetch()


@pytest.mark.asyncio
async def test_variants_get_vcf_path_not_found():
    """Test get_vcf_path() raises FileNotFoundError when VCF not in files."""
    variants = Variants(sample_id="NA12829", vcf_name="test.vcf", files=[])

    with pytest.raises(FileNotFoundError, match="VCF file test.vcf not found"):
        variants.get_vcf_path()


@pytest.mark.asyncio
async def test_variants_get_vcf_path_not_cached():
    """Test get_vcf_path() raises error when file not in cache."""
    # Create IpFile without local_path (not fetched yet)
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="test.vcf",
        size=1000,
        keyvalues={"type": "variants"},
        created_at=datetime.now(),
        local_path=None,  # Not downloaded yet
    )

    variants = Variants(sample_id="NA12829", vcf_name="test.vcf", files=[vcf_file])

    with pytest.raises(FileNotFoundError, match="not in cache"):
        variants.get_vcf_path()


@pytest.mark.asyncio
async def test_variants_properties():
    """Test Variants properties read from VCF file keyvalues."""
    # Create VCF file with metadata in keyvalues
    vcf_file = IpFile(
        id="test-vcf-id",
        cid="QmTest",
        name="test.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "caller": "deepvariant",
            "variant_type": "gvcf",
        },
        created_at=datetime.now(),
    )

    variants = Variants(
        sample_id="NA12829",
        vcf_name="test.vcf",
        files=[vcf_file],
    )

    # Properties should read from VCF file keyvalues
    assert variants.caller == "deepvariant"
    assert variants.is_gvcf is True

    # Create Variants with VCF type
    vcf_file2 = IpFile(
        id="test-vcf-id-2",
        cid="QmTest2",
        name="test2.vcf",
        size=1000,
        keyvalues={
            "type": "variants",
            "caller": "haplotypecaller",
            "variant_type": "vcf",
        },
        created_at=datetime.now(),
    )

    variants2 = Variants(sample_id="NA12829", vcf_name="test2.vcf", files=[vcf_file2])

    assert variants2.caller == "haplotypecaller"
    assert variants2.is_gvcf is False

    # Test with missing metadata
    vcf_file3 = IpFile(
        id="test-vcf-id-3",
        cid="QmTest3",
        name="test3.vcf",
        size=1000,
        keyvalues={"type": "variants"},
        created_at=datetime.now(),
    )

    variants3 = Variants(sample_id="NA12829", vcf_name="test3.vcf", files=[vcf_file3])

    assert variants3.caller == "unknown"
    assert variants3.is_gvcf is False
